# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FeatureList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FeatureList
  pod 'MercadoPagoSDK', :path => '/Users/mlmartins/Desktop/Projeto/px-ios'

end
